version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
    - 'db'
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: graphql
            schema: public
            user: postgres
            password: password
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true